### ISSUE TITLE
Is CNNconformer required?

### ISSUE THREAD

**Issue by skol101** [fss1t/CausalStarGANv2-VC#1]
Hello, and thank you for releasing your model.

The question I've got is that one of components (CNNconformer) needs lab . mono files. Since I'm using vctk + custom dataset (without text labels for each wave file), creating text labels is quite tiresome. Is there an alternative to using CNNconformer? 

I've found this model https://github.com/lingjzhu/charsiu which can create TextGrid files using predictive alignment. 

Cheers, and waiting for your reply.

**Comment by fss1t** [comment]
Hello. Thank you for using my model.

VCTK lab files are provided by Mr. kan-bayashi. 
(https://github.com/kan-bayashi/VCTKCorpusFullContextLabel)
Even with other custom dataset, the phonemes are assumed to be recognized by CNNConformer trained on VCTK multi-speaker utterances.

**Comment by skol101** [comment]
Yep, I've got the full context labels for VCTK too. But there are no text labels (thus, no lab mono files) for custom VCTK-like dataset. Looks like I have to run Charsiu with predictive aligner on the custom dataset, and then somehow convert Textgrid files to lab files.

What do you think?

**Comment by skol101** [comment]
I think I've found what I need https://github.com/prosodylab/prosodylab.alignertools

**Comment by fss1t** [comment]
Sorry, I'm only familiar with Japanese alignment. But I think CTC is also possible.

**Comment by skol101** [comment]
I've noticed that VCTK mono labels have different timestamps . They must be in mil seconds instead of seconds as in JVS dataset, correct? 
```
         0    1500000 pau
   1500000    4500000 pau
   4500000    6050000 pau
   6050000   13450000 s
  13450000   13600000 ih
  13600000   14400001 k
  14400001   15150000 s
  15150000   17100000 s
  17100000   17250000 p
  17250000   32550001 uw
  32550001   32700000 n
  32700000   32850001 z
  32850001   33000000 ah
  33000000   33150001 v
  33150001   33850000 f
  33850000   34050000 r
  34050000   34349999 eh
  34349999   34500000 sh
  34500000   35300000 s
  35300000   35450001 n
  35450001   35599999 ow
  35599999   37049999 p
  37049999   37200000 iy
  37200000   37449999 z
  37449999   37950001 pau
  37950001   48649998 f
  48649998   48800001 ay
  48800001   48950000 v
  48950000   49099998 th
  49099998   49250002 ih
  49250002   49400001 k
  49400001   49699998 s
  49699998   49850001 l
  49850001   50050001 ae
  50050001   50200000 b
  50200000   51350002 z
  51350002   51500001 ah
  51500001   51650000 v
  51650000   51799998 b
  51799998   51950002 l
  51950002   57900000 uw
  57900000   59200001 ch
  59200001   59349999 iy
  59349999   59499998 z
  59499998   59850001 pau
  59850001   62249999 ae
  62249999   62399998 n
  62399998   62550001 d
  62550001   62700000 m
  62700000   62849998 ey
  62849998   66500001 b
  66500001   66650000 iy
  66650000   66799998 ax
  66799998   67900000 s
  67900000   68049998 n
  68049998   68200002 ae
  68200002   68400002 k
  68400002   73099999 f
  73099999   78550000 ao
  78550000   78699999 r
  78699999   78899999 hh
  78899999   79050002 er
  79050002   79200001 b
  79200001   79349999 r
  79349999   79499998 ah
  79499998   79650002 dh
  79650002   79800000 er
  79800000   79949999 b
  79949999   80100002 aa
  80100002   80249996 b
  80249996   81750002 pau
  81750002   83549995 pau

**Comment by fss1t** [comment]
HTK labels are calcurated with sec*1e7. (line 49 in https://github.com/r9y9/deepvoice3_pytorch/blob/master/vctk_preprocess/prepare_htk_alignments_vctk.py)
So please insert them after line 49 in https://github.com/fss1t/CausalStarGANv2-VC/blob/main/CNNConformer/CNNConformer/train/dataset.py.
`time_start_phoneme*=1e-7`
`time_end_phoneme*=1e-7`

**Comment by skol101** [comment]
I used this https://github.com/nltk/nltk_contrib/blob/95d1806e2f4e89e960b76a685b1fba2eaa7d5142/nltk_contrib/textgrid.py to  generate lab files from TextGrid files generated by https://github.com/lingjzhu/charsiu (using Textless aligner).

So my lab files look like these. Will this work with the CNNconformer?
```
0 0.07 sil
0.07 0.09 s
0.09 0.19 eh
0.19 0.23 sil
0.23 0.27 y
0.27 0.3 uh
0.3 0.31 er
0.31 0.36 r
0.36 0.49 s
0.49 0.67 aw
0.67 0.71 n
0.71 0.73 v
0.73 0.77 w
0.77 0.78 l
0.78 0.94 ao
0.94 0.96 l
0.96 1.01 m
1.01 1.26 er
1.26 1.3 sil
1.3 1.36 l
1.36 1.38 dh
1.38 1.45 eh
1.45 1.57 sil
1.57 1.59 er
1.59 1.69 ah
1.69 1.78 l
1.78 1.79 sil
1.79 2.04 iy
2.04 2.09 sil
2.09 2.16 d
2.16 2.25 uw
2.25 2.34 s
2.34 2.42 ah
2.42 2.46 m
2.46 2.49 th
2.49 2.53 ih
2.53 2.57 ng
2.57 2.6 hh
2.6 2.76 uw
2.76 2.83 m
2.83 3 er
3 3.08 sil
3.08 3.2 er
3.2 3.26 dh
3.26 3.38 ow
3.38 3.43 z
3.43 3.58 ow
3.58 3.63 l
3.63 3.71 d
3.71 3.79 s
3.79 3.89 ih
3.89 3.94 m
3.94 4 s
4 4.07 ah
4.07 4.11 n
4.11 4.16 z
4.16 4.19 ah
4.19 4.2 er
4.2 4.22 v
4.22 4.27 g
4.27 4.31 uh
4.31 4.34 d
4.34 4.5 ae
4.5 4.54 n
4.54 4.59 d
4.59 4.67 ah
4.67 4.68 p
4.68 4.72 th
4.72 4.76 ih
4.76 4.8 ng
4.8 4.86 m
4.86 4.9 ao
4.9 4.98 r
4.98 5.02 dh
5.02 5.07 ah
5.07 5.13 n
5.13 5.14 eh
5.14 5.3 ey
5.3 5.34 sil
```
