### ISSUE TITLE
Hifigan hyper params and training

### ISSUE THREAD

**Issue by skol101** [fss1t/CausalStarGANv2-VC#4]
I've started training, but validation melspec error doesn't really decline.

![Screenshot from 2022-02-20 16-14-39](https://user-images.githubusercontent.com/53978091/204007885-df0af483-4090-4222-bb00-03d92c055006.png)

I've noticed params for 24k are quiet different from the ones used here https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/egs/vctk/voc1/conf/hifigan.v1.yaml

```python
    "num_mels": 80,
    "num_freq": 1025,
    "n_fft": 1024,
    "hop_size": 256,
    "win_size": 1024,

    "sampling_rate": 24000,
```

**Comment by skol101** [comment]
But I can already hear that 20k sounds much better than 10k, so I guess subjective quality is more important than loss_g_melspec

Update after 30k the eval loss is going down and at 200k the quality is good.

**Comment by skol101** [comment]
But still would like to hear why hyper params are diferrent for 24k sampling

**Comment by fss1t** [comment]
Hyperparameters conform to https://github.com/jik876/hifi-gan.

**Comment by skol101** [comment]
Thanks
