### ISSUE TITLE
Possible to use pre-trained hifigan instead of training from scratch? 

### ISSUE THREAD

**Issue by skol101** [fss1t/CausalStarGANv2-VC#5]
There's already pre-trained Hifigan on VCTK set. I could only fine-tune to my dataset, instead of training it from the start, thus saving processing time.

**Comment by fss1t** [comment]
CausalHiFi-GAN model structure is not compatible with HiFi-GAN, so you cannot use pre-trained models of HiFi-GAN.

**Comment by skol101** [comment]
Ok
